export const PATHS = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  SAVED: '/saved',
  RECENT: '/recent',
  SHARE_LOCATION: '/share-location',
  VERIFY_EMAIL: '/verify-email',
  PROFILE: '/profile',
  CAMERA: '/camera',
  NOTIFICATIONS: '/notification',
  ADMIN: '/admin',
  MANAGE_USERS: '/manage-users',
  MANAGE_REPORTS: '/manage-reports',
  MANAGE_PLACES: '/manage-places',
  CREATE_NOTIFICATION: '/create-notification',
  CREATE_CAMERA: '/create-camera',
};
