export const ReportTypes = {
  TRAFFIC_JAM: "TRAFFIC_JAM",
  FLOOD: "FLOOD",
  ACCIDENT: "ACCIDENT",
  ROADWORK: "ROADWORK",
};

export const CongestionLevels = {
  NO_CONGESTION: "NO_CONGESTION",
  POSSIBLE_CONGESTION: "POSSIBLE_CONGESTION",
  HEAVY_CONGESTION: "HEAVY_CONGESTION",
};